# Required packages for WebRtcPipeWireCamera + portal camera access:
# sudo pacman -S --needed xdg-desktop-portal xdg-desktop-portal-hyprland xdg-desktop-portal-gtk pipewire pipewire-pulse wireplumber
--ozone-platform=x11
--force-dark-mode
--gtk-version=4
--enable-features=WebRtcPipeWireCamera
