[general]
font-sans = "IosevkaTermSlab Nerd Font"
font-mono = "IosevkaTermSlab Nerd Font"

[bar]
padding = 0.0
padding-ends = 0.0
module-gap = 0.0
button-variant = "basic"
button-bg-opacity = 0
button-icon-padding = 0.5
button-label-weight = "bold"
button-rounding = "none"

[[bar.layout]]
monitor = "*"
show = true
left = [
    "hyprland-workspaces",
    "cava",
]
center = ["media"]
right = [
    "systray",
    "clock",
    "volume",
    "cpu",
    "ram",
    "notifications",
    "network",
    "bluetooth",
    "dashboard",
]

[styling]
scale = 1.0
rounding = "none"

[styling.palette]
bg = "#131a24"
surface = "#192330"
elevated = "#212e3f"
fg = "#cdcecf"
fg-muted = "#71839b"
primary = "#719cd6"
red = "#c94f6d"
yellow = "#dbc074"
green = "#81b29a"
blue = "#63cdcf"

[modules.bluetooth]
label-show = false

[modules.cava]
bars = 48
noise-reduction = 0.1
style = "peaks"
bar-gap = 2
internal-padding = 0.0

[modules.clock]
format = "%H:%M:%S"
dropdown-show-seconds = true

[modules.network]
label-show = false

[modules.notifications]
popup-position = "bottom-right"
popup-close-behavior = "remove"

[modules.weather]
location = "London"
time-format = "24h"

[wallpaper]
transition-type = "center"
transition-duration = 2.0
transition-fps = 120
